// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTcnbwbYVy1tsKA7eUIlT6PsdBm6x7Cts',
    appId: '1:884888645758:web:778cd4bcde1f898d55a82f',
    messagingSenderId: '884888645758',
    projectId: 'mad-activity13',
    authDomain: 'mad-activity13.firebaseapp.com',
    storageBucket: 'mad-activity13.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvmUOf91qbszOUnk8z_JQuHXEOJF053Y4',
    appId: '1:884888645758:android:004690c64f8fe3e655a82f',
    messagingSenderId: '884888645758',
    projectId: 'mad-activity13',
    storageBucket: 'mad-activity13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUhsJe3B8c5f2vOfnUy10N-epZD283I7o',
    appId: '1:884888645758:ios:717121f3915fc8e455a82f',
    messagingSenderId: '884888645758',
    projectId: 'mad-activity13',
    storageBucket: 'mad-activity13.firebasestorage.app',
    iosBundleId: 'com.example.activity13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUhsJe3B8c5f2vOfnUy10N-epZD283I7o',
    appId: '1:884888645758:ios:717121f3915fc8e455a82f',
    messagingSenderId: '884888645758',
    projectId: 'mad-activity13',
    storageBucket: 'mad-activity13.firebasestorage.app',
    iosBundleId: 'com.example.activity13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTcnbwbYVy1tsKA7eUIlT6PsdBm6x7Cts',
    appId: '1:884888645758:web:7d82ada158bb933055a82f',
    messagingSenderId: '884888645758',
    projectId: 'mad-activity13',
    authDomain: 'mad-activity13.firebaseapp.com',
    storageBucket: 'mad-activity13.firebasestorage.app',
  );
}
